config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  root 'users#show'
                     
  resources :users, only: [:show, :index]
  
  resource :attendances do
    get 'date/:date', to: 'attendances#date'
    get '/index', to: 'attendances#index'
     collection { post :import }
  end
  resource :reserves do
    get '/index', to: 'reserves#index'
    get '/date', to: 'reserves#list'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>スケジュール管理アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="p-3 mb-2 bg-dark text-white clearfix">
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-8 text-center">
           <h3>ログインユーザー : 「<%= @user.name %>」</h3> 
        </div>
        <div class="col-4 text-right">
          <%= link_to '予約状況', user_path(current_user), data: {"turbolinks" => false}, class: "btn btn-cblue m-1" %>
          <%= link_to '勤怠編集ページ', attendances_path, data: {"turbolinks" => false}, class: "btn btn-cred m-1" %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-secondary m-1" %>  
        </div>
    </div> 
      <% else %>
      
        <div class="float-right">
          <div class="row">
            <div class="mx-1">
              <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary" %>
              <%= link_to '新規ユーザー作成', new_user_registration_path, data: {"turbolinks" => false}, class: "btn btn-cgreen m-1"%>
            </div>
          </div>
        </div>
       
       <% end %>
    </header>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>